This is makeindex, version 2.15 [TeX Live 2017] (kpathsea + Thai support).
Scanning style file ./dp_kolarto5.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file dp_kolarto5.acn....done (339 entries accepted, 0 rejected).
Sorting entries......done (3307 comparisons).
Generating output file dp_kolarto5.acr....done (105 lines written, 0 warnings).
Output written in dp_kolarto5.acr.
Transcript written in dp_kolarto5.alg.
